### ISSUE TITLE
Remove the upper limit of hex digits in Unicode code point escapes

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/regexpu#12]
E.g. `'\u{00000000000000000001D306}' == '\u{1D306}'`.

The following dependencies need patching:

- [x] [regjsparser: done in v0.1.3](https://github.com/jviereck/regjsparser/releases/tag/0.1.3)
- [x] Esprima: https://github.com/ariya/esprima/pull/293 (master) & https://github.com/ariya/esprima/pull/294 (harmony)
- [x] esprima-fb (used by recast by default): https://github.com/facebook/esprima (https://github.com/facebook/esprima/issues/77)
- [ ] recast: https://github.com/benjamn/recast/pull/142

**Comment by jeffmo** [comment]
Hey all, just FYI:

I just published `esprima-fb@9001.1.0-dev-harmony-fb` which includes the patches you mentioned were blocking this issue

**Comment by mathiasbynens** [comment]
Thanks for the heads up, @jeffmo! Much appreciated.
