### ISSUE TITLE
doesn't recognize unicode character classes

### ISSUE THREAD

**Issue by Lwangaman** [mathiasbynens/regexpu#14]
I'm not sure if this is intended because I'm not sure if ECMA 6 intends on supporting this or not, but I see the compiler is not liking unicode character classes ( "\p" in posix regexes).
For example: 
`var match = string.match(/\p{L&}/u);`
is not liked by the transpiler.

**Comment by mathiasbynens** [comment]
ES6 does not support this. If you’d like this to be part of ES7, see <https://github.com/mathiasbynens/es6-unicode-regexp-proposal/blob/master/p.md>.

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/regexpu-core/blob/master/property-escapes.md

**Comment by Loilo** [comment]
Now that Unicode character classes are stage 4, will this use case be reconsidered? 🙂
