### ISSUE TITLE
Specifying astral plane character range in surrogate form

### ISSUE THREAD

**Issue by nhahtdh** [mathiasbynens/regexpu#20]
Does the draft spec says anything about this use case?

    /[\uD80C\uDC00-\uD80D\uDC1F]/u

I expect it to behave the same as

    /[\u{13000}-\u{1342F}]/u

since

    /[\uD80C\uDC00\uD80D\uDC1F]/u

(without the range) is correctly recognized as 2 separate characters by regexpu.

**Comment by mathiasbynens** [comment]
Can you confirm this, @allenwb?

**Comment by mathiasbynens** [comment]
This is how I understand the spec:

1. `/[\uD80C\uDC00-\uD80D\uDC1F]/u` throws because it attempts to create a range between `\uDC00` and `\uD80D` which is in the wrong order.
2. `/[\u{13000}-\u{1342F}]/u` works as expected.
3. `/[\uD80C\uDC00\uD80D\uDC1F]/u` — regexpu currently treats this as `/[\u{13000}\u{1342F}]/u`, but given point 1 above that may not be correct.

**Comment by mathiasbynens** [comment]
Given https://github.com/mathiasbynens/regexpu/issues/15 and https://bugs.ecmascript.org/show_bug.cgi?id=3521#c3, I think the bug is with 1. `/[\uD80C\uDC00-\uD80D\uDC1F]/u` should be treated as `/[\u{13000}-\u{1342F}]/u`.

**Comment by mathiasbynens** [comment]
The problem is `var x = /[\uD834\uDF06-\uD834\uDF08a-z]/u;` doesn’t parse in Esprima. https://github.com/jquery/esprima/pull/1100

**Comment by allenwb** [comment]
@mathiasbynens yes, `/[\uD80C\uDC00-\uD80D\uDC1F]/u` means the same thing as `/[\u{13000}-\u{1342F}]/u` because the surrogate pair form is recognized as a *RegExpUnicodeEscapeSequence* by the RegExp pattern grammar in U mode.

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/regexpu/compare/20 still waiting for Esprima to release a version that includes the fix, and Recast to update its Esprima dependency accordingly.

**Comment by mathiasbynens** [comment]
https://github.com/benjamn/recast/issues/178

**Comment by mathiasbynens** [comment]
Got tired of waiting for https://github.com/mathiasbynens/regexpu/issues/20#issuecomment-93765713 to be resolved, so introduced an explicit dependency on Esprima v2.6.0+ instead.

Once Recast updates its Esprima dependency, we can drop ours.

**Comment by mathiasbynens** [comment]
> Once Recast updates its Esprima dependency, we can drop ours.

It happened! https://github.com/benjamn/recast/issues/178#issuecomment-171720421
