### ISSUE TITLE
clear input

### ISSUE THREAD

**Issue by cup** [mathiasbynens/regexpu#67]
With Firefox, if I click "Clear Recent History" with:

~~~
Time range to clear: Everything
Details:
- Cache
- Offline Website Data
- Site Preferences
~~~

Then refresh the page, my previous input remains. Only workaround ive found is
to open private window

**Comment by cup** [comment]
a look at the source shows that page is using local storage. running

~~~js
localStorage.clear();
~~~

followed by Ctrl + F5 seems to do it

**Comment by mathiasbynens** [comment]
Yep, it's `localStorage`.
