### ISSUE TITLE
Valid pattern with unescaped dot fails to rewrite

### ISSUE THREAD

**Issue by juliangoacher** [mathiasbynens/regexpu#69]
The `rewritePattern` function generates an error when passed a regex pattern containing an unescaped dot within an alternatives group.

For example, the following pattern:
```
    /(x.x|x)/
```
Fails to rewrite in the following code:
```
const regex = /(x.x|x)/
const pattern = regex.toString()
rewritePattern(pattern)
```
And instead generates the following error:
```
Error: Invalid node type: dot; expected types: /^(?:anchor|characterClass|characterClassEscape|empty|group|quantifier|reference|unicodePropertyEscape|value)$/
```
The error goes away if the dot is escaped:
```
    /(x\.x|x)/
```
But of course this changes the meaning of the regex.

The problem is seen in the current regexpu version (4.6.0) but doesn't seem to exist in the previous version (tested 4.5.4).

**Comment by mathiasbynens** [comment]
Thanks for the report! This is a regexpu-core issue.

**Comment by juliangoacher** [comment]
@mathiasbynens Should I raise the issue on that project instead then?

**Comment by mathiasbynens** [comment]
@juliangoacher That'd be awesome, thank you! Getting rid of some indirection, the minimal repro you provided is:

```js
rewritePattern('/(x.x|x)/');
```

Feel free to post it on the new bug. Thank you!

**Comment by juliangoacher** [comment]
@mathiasbynens Sure - wrote it the way I did just to emphasise that the pattern is a valid regex. I'll raise a new bug on regexpu-core.

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/regexpu-core/issues/33
