### ISSUE TITLE
Assertion error '\\u03B8' == '[\\u03B8\\u03F4]'

### ISSUE THREAD

**Issue by SnarkBoojum** [mathiasbynens/regexpu#71]
Strangely, the Debian package for regexpu got broken recently, and since I didn't change anything, I don't know exactly what the reason is. [Here is the link to the bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=963374)

**Comment by SnarkBoojum** [comment]
A better report was made.

**Comment by mathiasbynens** [comment]
Do you mean https://github.com/mathiasbynens/regexpu-core/issues/44?

**Comment by SnarkBoojum** [comment]
Yes.
