### ISSUE TITLE
`/[\u{11450}\u{11C50}\u{11C52}]/u`

### ISSUE THREAD

**Issue by Yaffle** [mathiasbynens/regexpu#72]
Sorry, if I report a bug in a wrong place and not sure if the online demo has the latest code.

for the regexp in the title, the last part is lost:
`/(?:[\uD805\uD807]\uDC50)/`, which matches only 2 code points, not 3.

Update:
it is a bug in "regenerate.js" in `optimizeByLowSurrogates`, seems:
```javascript

// String.fromCodePoint(0x11450) === String.fromCharCode(0xD805, 0xDC50)
// String.fromCodePoint(0x11C50) === String.fromCharCode(0xD807, 0xDC50)
// String.fromCodePoint(0x11C52) === String.fromCharCode(0xD807, 0xDC52)

var set = regenerate()
  .add(0x11450)
  .add(0x11C50)
  .add(0x11C52)
  ;
console.log(set.toString());
```

**Comment by mathiasbynens** [comment]
This was fixed in regexpu-core. Thanks again for reporting + patching this, @Yaffle!
