### ISSUE TITLE
`/^.$/us` is transpiled incorrectly

### ISSUE THREAD

**Issue by thorn0** [mathiasbynens/regexpu#74]
Current output:
```js
const transpiled = /^(?:[\0-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])$/
```
Actual result:
```js
transpiled.test('\u0001\udc00'); // true
```
Expected result:
```js
/^.$/us.test('\u0001\udc00'); // false
```

**Comment by jridgewell** [comment]
It's last branch `(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]` which is causing the error. `(?:[^\uD800-\uDBFF]|^)` is eating the `\u0001` and `[\uDC00-\uDFFF]` is matching the `\udc00`.  See https://github.com/mathiasbynens/regexpu/issues/17 for context why this happens, and https://github.com/mathiasbynens/regenerate/issues/28. Unfortunately, it's not possible to implement correctly without lookbehinds.

**Comment by mathiasbynens** [comment]
This is the fourth bullet point on <https://github.com/mathiasbynens/regexpu#known-limitations>:

> 4. _regexpu_ [doesn’t match lone low surrogates accurately](https://github.com/mathiasbynens/regexpu/issues/17). Unfortunately that is impossible to implement due to the lack of lookbehind support in JavaScript regular expressions.

JSC/Safari still doesn't support lookbehinds, so this phrasing is still accurate even for projects that only need to consider modern JS environments. :(
